Ad_como/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^account/', include('account.urls')),
    url(r'^todolist/', include('to_do_list.urls'), name='todolist'),
]

to_do_list/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',
        views.Index.as_view(), name='index'),
    url(r'^details/(?P<task_id>\d{1,50})/',
        views.details, name='details'),
    url(r'^subtasks/(?P<subtask_id>\d{0,50})/complete/',
        views.complete_subtask, name='complete_subtask'),
    url(r'^subtasks/(?P<subtask_id>\d{0,50})/delete/',
        views.delete_subtask, name='delete_subtask'),
    url(r'^subtasks/(?P<subtask_id>\d{0,50})/repair/',
        views.repair_subtask, name='repair_subtask'),
    url(r'^lists/add/',
        views.add_list, name='add_list'),
    url(r'^lists/completed/',
        views.completed, name='completed'),
    url(r'^lists/trash/',
        views.trash, name='trash'),
    url(r'^lists/today/',
        views.today, name='today'),
    url(r'^lists/next-week/',
        views.next_week, name='next_week'),
    url(r'^lists/(?P<list_id>\d{0,50})/',
        views.ListDetails.as_view(), name='list_details'),
    url(r'^lists/(?P<list_id>\d{0,50})/edit/',
        views.edit_list, name='edit_list'),
    url(r'^lists/(?P<list_id>\d{0,50})/delete/',
        views.delete_list, name='delete_list'),
    url(r'^lists/(?P<list_id>\d{0,50})/invite/',
        views.invite, name='invite'),
    url(r'^lists/(?P<list_id>\d{0,50})/exit/',
        views.exit_list, name='exit_list'),
    url(r'^lists/(?P<list_id>\d{0,50})/kick/(?P<user_id>\d{0,50})/',
        views.kick, name='kick_user'),
    url(r'^tags/add/$',
        views.add_tag, name='add_tag'),
    url(r'^tags/(?P<tag_id>\d{0,50})/edit/',
        views.edit_tag, name='edit_tag'),
    url(r'^tags/(?P<tag_id>\d{0,50})/delete/',
        views.delete_tag, name='delete_tag'),
    url(r'^tags/details/(?P<tag_id>\d{0,50})/',
        views.TagDetails.as_view(), name='tag_details'),
    url(r'^edit/(?P<task_id>\d{0,50})/',
        views.edit_task, name='edit_task'),
    url(r'^trash/(?P<task_id>\d{0,50})/',
        views.trash_task, name='trash_task'),
    url(r'^delete/(?P<task_id>\d{0,50})/',
        views.delete_task, name='delete_task'),
    url(r'^complete/(?P<task_id>\d{0,50})/',
        views.complete_task, name='complete_task'),
    url(r'^repair/(?P<task_id>\d{0,50})/',
        views.repair_task, name='repair_task'),
    url(r'^add/',
        views.add, name='add')
]

to_do_list/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from multiselectfield import MultiSelectField
from .consts import STATUS_FOR_SUBTASK, STATUS, PERIODS, DAYS, PRIORITIES


class Tag(models.Model):
    users = models.ManyToManyField(User, default=None, blank=True)
    name = models.CharField(_('name'), max_length=20)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('tags')

    def __str__(self):
        return '%s' % self.name

class TaskList(models.Model):
    name = models.CharField(_('name'), max_length=20)
    is_private = models.BooleanField(_('is_private'), default=True)
    users = models.ManyToManyField(User, related_name=('all_lists'), default=None, blank=True)
    created_user = models.ForeignKey(User, related_name=('created_lists'), on_delete=models.CASCADE, default=None,
                                     null=True, blank=True)

    class Meta:
        verbose_name = _('task list')
        verbose_name_plural = _('task lists')

    def __str__(self):
        return '%s' % self.name

class Task(models.Model):
    title = models.CharField(_('title'), max_length=250)
    description = models.CharField(_('description'), max_length=250)
    created = models.DateTimeField(_('created'), auto_now=True, null=False, blank=True)
    deadline = models.DateTimeField(_('deadline'), blank=True, default=None, null=True)
    created_user = models.ForeignKey(User, related_name=('created_tasks'), on_delete=models.CASCADE, default=None,  # если удаляем юзера, то удаляются се таски, которые закреплены за юзером
                                     null=True, blank=True)
    completed_user = models.ForeignKey(User, related_name=('completed_tasks'), on_delete=models.CASCADE, default=None,
                                       null=True, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)

    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE, default=None, blank=True)
    priority = models.CharField(_('priority'), choices=PRIORITIES, max_length=255, default=-1)
    status = models.CharField(_('status'), choices=STATUS, default='P', max_length=1)
    repeat_days = MultiSelectField(_('repeat days'),max_length=10, max_choices=7, choices=DAYS, null=True, blank=True)
    period_count = models.IntegerField(_('period count'), default=0, blank=True)
    period_val = models.CharField(max_length=1, choices=PERIODS, blank=True, default='N')

    class Meta:
        verbose_name = _('task')
        verbose_name_plural = _('tasks')
        ordering = ('deadline',)

    def save(self, *args, **kwargs): # чтобы в create было реальное время указано
        if not self.id:
            self.created = timezone.now()
        return super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class SubTask(models.Model):
    title = models.CharField(_('title'),max_length=100)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, blank=False, null=False)
    status = models.CharField(max_length=1, default='P', choices=STATUS_FOR_SUBTASK)

    class Meta:
        verbose_name = _('subtask')
        verbose_name_plural = _('subtasks')

    def __str__(self):
        return self.title

to_do_list/forms.py
from django.forms import ModelForm
from django import forms

from .models import Task


class TaskForm(ModelForm):
    def __init__(self):
        super(TaskForm, self).__init__()
        self.fields['title'].required = True

    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline', 'period_count', 'period_val', 'tags', 'task_list', 'repeat_days']
        localized_fields = ['deadline']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'deadline': forms.DateTimeInput(attrs={'class': 'form-control', 'id': 'deadline'}),
            'period_val': forms.Select(attrs={'class': 'form-control'}),
            'period_count': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'task_list': forms.Select(attrs={'class': 'form-control'}),
            'repeat_days': forms.SelectMultiple(attrs={'class': 'form-control'})
        }

to_do_list/views.py
from datetime import datetime, date, timedelta

from django.urls import reverse_lazy, reverse
from django.utils import timezone

from dateutil.relativedelta import *
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import TaskForm
from django.utils.translation import ugettext_lazy as _

from . import parsers
from .models import Task, TaskList, Tag, SubTask
from django.views import generic


@method_decorator(login_required(login_url='/account/login'), name='dispatch')
@method_decorator(parsers.checkable, name='dispatch')
class Index(generic.TemplateView):
    template_name = 'to_do_list/index.html'

    def get_context_data(self, **kwargs):
        sort_type = None
        if 'sort_type' in self.request.GET:
            sort_type = self.request.GET['sort_type']
        tasks = Task.objects.filter(
            (
                    (
                            Q(created_user=self.request.user) & Q(
                            task_list=None) |  # показывает задачи, которые юзер или создал или которые в таск листе
                            Q(task_list__in=self.request.user.all_lists.all())
                    )
                    &
                    (
                            Q(status='P') | Q(status='O')
                    )
            )
        )
        if sort_type:
            tasks = tasks.order_by(sort_type)

        page = self.request.GET.get('page', 1)
        paginator = Paginator(tasks, 8)
        try:
            tasks = paginator.page(page)
        except PageNotAnInteger:
            tasks = paginator.page(1)
        except EmptyPage:
            tasks = paginator.page(paginator.num_pages)
        kwargs['tasks'] = tasks
        return super().get_context_data(**kwargs)


@method_decorator(login_required(login_url='/account/login'), name='dispatch')
@method_decorator(parsers.checkable, name='dispatch')
class ListDetails(generic.TemplateView):
    template_name = 'to_do_list/list_details.html'

    def get_context_data(self, list_id, **kwargs):
        sort_type = None
        if 'sort_type' in self.request.GET:
            sort_type = self.request.GET['sort_type']

        task_list = get_object_or_404(TaskList, id=list_id, users__in=[self.request.user])
        tasks = task_list.task_set.filter(Q(status='P') | Q(status='O'))
        users = task_list.users.all()

        if sort_type:
            tasks = tasks.order_by(sort_type)

        page = self.request.GET.get('page', 1)
        paginator = Paginator(tasks, 8)                             # чтобы выводились постранично
        try:
            tasks = paginator.page(page)
        except PageNotAnInteger:
            tasks = paginator.page(1)
        except EmptyPage:
            tasks = paginator.page(paginator.num_pages)

        kwargs['tasks'] = tasks
        kwargs['users'] = users
        kwargs['list'] = task_list
        kwargs['superuser'] = self.request.user == task_list.created_user  # если суперюзер, то появляются какие то кнопки, а каке то проподают
        return super().get_context_data(**kwargs)


@method_decorator(login_required(login_url='/account/login'), name='dispatch')
class TagDetails(generic.TemplateView):
    template_name = 'to_do_list/tag_details.html'

    def get_context_data(self, tag_id, **kwargs):
        sort_type = None
        if 'sort_type' in self.request.GET:
            sort_type = self.request.GET['sort_type']

        tag = get_object_or_404(Tag, id=tag_id, users__in=[self.request.user])
        tasks = tag.task_set.filter((
                Q(created_user=self.request.user) & Q(task_list=None) |
                Q(task_list__in=self.request.user.all_lists.all())
        )).all()

        if sort_type:
            tasks = tasks.order_by(sort_type)

        page = self.request.GET.get('page', 1)
        paginator = Paginator(tasks, 8)
        try:
            tasks = paginator.page(page)
        except PageNotAnInteger:
            tasks = paginator.page(1)
        except EmptyPage:
            tasks = paginator.page(paginator.num_pages)

        kwargs['tasks'] = tasks
        kwargs['tag'] = tag
        return super().get_context_data(**kwargs)


@parsers.checkable
@login_required(login_url='/accounts/login')
def details(request, task_id):
    task = get_object_or_404(
        Task,
        Q(id=task_id) & (
                Q(created_user=request.user) & Q(task_list=None) |
                Q(task_list__in=request.user.all_lists.all())
        )
    )
    if request.method == 'POST':
        if task.status == 'C':
            task.status = 'P'
            task.save()
            parsers.check_overdue()

        try:
            title = request.POST['subtask_name']
        except KeyError:
            return HttpResponseBadRequest()
        st = SubTask(title=title, task=task)
        st.save()
    context = {
        'task': task,
        'pending_st': task.subtask_set.filter(status='P'),
        'completed_st': task.subtask_set.filter(status='C'),
    }
    return render(request, 'to_do_list/details.html', context)


@login_required(login_url='/account/login')
def add(request):
    if request.method == 'POST':
        try:
            title = request.POST['title']
            description = request.POST['description']
            tags = request.POST.getlist('tags')
            priority = request.POST['priority']
            list_id = request.POST.get('list_id')
            deadline = request.POST['deadline']
            period = request.POST['period']
            days = request.POST.getlist('days')
            count = int(request.POST['count'])
            dd = None
            if deadline != '':
                dd = datetime.strptime(deadline, settings.DATETIME_PATTERN)
            if not parsers.validate_data(priority, period, days, count):
                raise ValueError
        except (KeyError, ValueError, AttributeError, TypeError):
            return HttpResponseBadRequest()

        user = request.user
        if list_id:
            try:
                task_list = TaskList.objects.get(id=list_id)
                list_id = int(list_id)
            except (TaskList.DoesNotExist(), ValueError, TypeError):
                messages.error(request, 'Task list does not exist, created simple task', extra_tags='alert-error')
                list_id = None
        task = Task(
            title=title,
            description=description,
            created_user=user,
            priority=priority,
            deadline=dd,
            task_list_id=list_id
        )
        if dd:
            task.period_val = period
            task.period_count = count
            if period == 'W':
                task.repeat_days = days
        task.save()
        task.tags.clear()
        for tag in tags:
            try:
                task.tags.add(Tag.objects.get(id=int(tag)))
            except (ValueError, Tag.DoesNotExist):
                return HttpResponseBadRequest()
        task.save()
        messages.info(request, 'Task added', extra_tags='alert-success')
        return redirect('/todolist')
    form = TaskForm()
    return render(request, 'to_do_list/add.html', {'form': form})


@login_required(login_url='/account/login')
def add_list(request):
    if request.method == 'POST':
        try:
            name = request.POST['name']
        except KeyError:
            return HttpResponseBadRequest()
        is_private = 'is_private' in request.POST
        user = request.user
        task_list = TaskList(name=name, is_private=is_private, created_user=user)
        task_list.save()
        task_list.users.add(user)
        task_list.save()
        return redirect('/todolist')
    return render(request, 'to_do_list/add_tasklist.html')


@login_required(login_url='/account/login')
def add_tag(request):
    if request.method == 'POST':
        try:
            name = request.POST['name']
        except KeyError:
            return HttpResponseBadRequest()
        user = request.user
        tag = Tag(name=name)
        tag.save()
        tag.users.add(user)
        tag.save()
        return redirect('/todolist')
    return render(request, 'to_do_list/add_tag.html')


@login_required(login_url='/account/login')
def edit_list(request, list_id):
    if request.method == 'POST':
        try:
            name = request.POST['name']
        except KeyError:
            return HttpResponseBadRequest()
        is_private = 'is_private' in request.POST
        user = request.user
        task_list = get_object_or_404(TaskList, id=list_id, created_user=user)
        task_list.name = name
        task_list.is_private = is_private
        task_list.save()
        if is_private:
            task_list.users.clear()
            task_list.users.add(user)
            task_list.save()

        return redirect('/todolist/lists/' + str(list_id))

    task_list = get_object_or_404(TaskList, id=list_id, created_user=request.user)
    context = {
        'name': task_list.name,
        'is_private': task_list.is_private
    }
    return render(request, 'to_do_list/add_tasklist.html', context)


@login_required(login_url='/account/login')
def edit_task(request, task_id):
    if request.method == 'POST':
        try:
            title = request.POST['title']
            description = request.POST['description']
            tags = request.POST.getlist('tags')
            priority = request.POST['priority']
            list_id = request.POST.get('list_id')
            deadline = request.POST['deadline']
            period = request.POST['period']
            days = request.POST.getlist('days')

templates/to_do_list/add.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}

{% block title %}
<title> Ad_como - Add task </title>
{% endblock%}

{% block content %}
<form action="{% url 'add' %}" method="post">{% csrf_token %}

    <!-- <table class="table">{{ form.as_table }}</table> -->

    <label for="title">{% trans 'Title' %}</label>
    <br />
    <input class="form-control" type="text" name="title" id="title">
    <br />
    <label for="description">{% trans 'Description' %}</label>
    <br />
    <textarea class="form-control" name="description" id="description" > </textarea>
    <br />
    <label for="priority">{% trans 'Priority' %}</label>
    <select class="form-control" name="priority" id="priority">
        <option value="0">{% trans 'High' %}</option>
        <option value="1">{% trans 'Medium' %}</option>
        <option value="2">{% trans 'Low' %}</option>
        <option value="-1" selected="">{% trans 'None' %}</option>
    </select>
    <br />

    <div class="form-row field-tags">
        <div>
            <label for="id_tags">{% trans 'Tags' %}:</label>
            <div class="related-widget-wrapper">
                <select class="form-control" name="tags" id="id_tags" multiple="multiple">
                    {% for tag in tags %}
                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="help">{% trans 'Hold down "Control", or "Command" on a Mac, to select more than one.' %}</div>
        </div>
    </div>
    <br />
    <div class="form-row field-tags">
        <div>
            <label for="list_id">{% trans 'List' %}:</label>
            <div class="related-widget-wrapper">
                <select class="form-control" name="list_id" id="list_id">
                    {% for list in task_lists %}
                    <option value="{{ list.id }}">{{ list.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="help">{% trans 'Hold down "Control", or "Command" on a Mac, to select more than one.' %}</div>
        </div>
    </div>
    <br />
    <div>
        <label for="deadline">{% trans 'Deadline' %}:</label>
        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <div class='input-group date' id='deadline'>
                        <input type='text' class="form-control" name="deadline" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $(function () {
                    $('#deadline').datetimepicker();
                });
            </script>
        </div>
    </div>

    <div class="row">
        <div class="col col-sm-2">
            <label for="period">{% trans 'Repeat every' %}:</label>
            <input type="number" min="1" name="count" class="form-control" style="margin-bottom:10px" value="1">
            <select class="form-control" name="period" id="period">
                <option value="D">{% trans 'Day' %}</option>
                <option value="W">{% trans 'Week' %}</option>
                <option value="M">{% trans 'Month' %}</option>
                <option value="Y">{% trans 'Year' %}</option>
                <option value="N" selected>{%  trans 'None' %}</option>
            </select>
        </div>
        <div class="col col-sm-2">
            <label for="days">{% trans 'Days' %}:</label>
            <select class="form-control"  name="days" id="days" multiple="multiple">
                <option value="1">{% trans 'Monday' %}</option>
                <option value="2">{% trans 'Tuesday' %}</option>
                <option value="3">{% trans 'Wednesday' %}</option>
                <option value="4">{% trans 'Thursday' %}</option>
                <option value="5">{% trans 'Friday' %}</option>
                <option value="6">{% trans 'Saturday' %}</option>
                <option value="7">{% trans 'Sunday' %}</option>
            </select>
        </div>
    </div>

    <br />
    <input type="submit" class="btn btn-light" value="submit">

    <script>
        if (top != self) { top.location.replace(self.location.href); }
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-47462200-1', 'eonasdan.github.io');
        ga('send', 'pageview');
    </script>
</form>
{% endblock%}

templates/to_do_list/add_tasklist.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}

{% block title %}
<title> Ad_como - Add tasklist </title>
{% endblock%}

{% block content %}
<form method="post" class="form-group">
    {% csrf_token %}
    <label for="name">{% trans 'Name' %}</label>
    <br />
    <input class="form-control" type="text" name="name" id="name" value="{{ name }}">
    <br />
    <label for="is_private"><input type="checkbox" name="is_private" id="is_private" value="{{ is_private }}">{% trans 'Private' %}</label>
    <br />
    <input class="btn" type="submit" value="Submit">
</form>
{% endblock%}

templates/to_do_list/completed.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}

{% block title %}
<title> Ad_como - Trash </title>
{% endblock%}

{% block content %}
<h5>{% trans 'Tasks' %}:</h5>
<ul>
    {% for task in tasks %}
    <li>
        <a href="{% url 'details' task_id=task.id %}">{{ task.title }}</a> : {{task.description}}
        <form action="{% url 'repair_task' task_id=task.id %}" class="task_form">
            <input type="submit" class="btn btn-link" value={% trans 'Repair' %} />
        </form>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/to_do_list/details.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}

{% block title %}
<title> Ad_como - Task info </title>
{% endblock%}

{% block content %}
<div class="container" style="width: 100%;">
    <div class="row">
        <div class="col col-sm-6">
            <h1>{{task.title}}</h1>

            {% if task.status != 'C' %}
            <a href="{% url 'complete_task' task_id=task.id %}?next={{request_path}}" class="btn btn-link">{% trans 'Complete' %}</a>
            {% else %}
            <a href="{% url 'repair_task' task_id=task.id %}?next={{request_path}}" class="btn btn-link">{% trans 'Repair' %}</a>
            {% endif %}
            {% if task.created_user == user %}
            <a href="{% url 'edit_task' task_id=task.id %}?next={{request_path}}" class="btn btn-link">{% trans 'Edit' %}</a>
            <a href="{% url 'trash_task' task_id=task.id %}?next={{request_path}}" class="btn btn-link">{% trans 'Trash' %}</a>
            {% endif %}

            <p>{% trans 'Description' %}:&nbsp {{ task.description }} </p>
            <p>{% trans 'Created' %}:&nbsp {{ task.created }} </p>
            <p>{% trans 'Deadline' %}: &nbsp {{ task.deadline }} </p>
            {% if task.period_val != 'N' %}
            <p>{% trans 'Repeat every' %}: &nbsp {{ task.period_count }} &nbsp {{task.get_period_val_display }}(s) </p>
            {% endif %}
            {% if task.period_val == 'W' %}
            <p>{% trans 'At' %}: &nbsp {{ task.repeat_days }} </p>
            {% endif %}
            <p>{% trans 'Created user' %}:&nbsp {{ task.created_user }} </p>
            {% if task.status == 'C' %}
            <p>{% trans 'Completed user' %}:&nbsp {{ task.completed_user }} </p>
            {% endif %}
            <p>{% trans 'Task list' %}:&nbsp {{ task.task_list }} </p>
            <p>{% trans 'Status' %}:&nbsp {{ task.get_status_display }} </p>
            <p>{% trans 'Priority' %}:&nbsp {{ task.get_priority_display }} </p>
            <h5>{% trans 'Tags' %}:</h5>
            <ul>
                {% for tag in task.tags.all %}
                <li>
                    {{tag}}
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col col-sm-6">
            <h3>{% trans 'Subtasks' %}:</h3>
            <form method="post" class="form-group">
                {% csrf_token %}
                <label for="subtask_name">{% trans 'Name' %}</label>
                <div class="input-group">
                    <input type="text" id="subtask_name" name="subtask_name" class="form-control">
                    <input type="submit" class="btn btn-success">
                </div>
            </form>
            <hr>
            <h2>{% trans 'Pending' %}</h2>
            <ul class="list-group">
                {% for st in pending_st %}
                <li>{{st.title}}
                    <a href="{% url 'complete_subtask' subtask_id=st.id %}" class="btn btn-link">{% trans 'Complete' %}</a>
                    <a href="{% url 'delete_subtask' subtask_id=st.id %}" class="btn btn-link">{% trans 'Delete' %}</a>
                </li>
                {% endfor %}
            </ul>
            <hr>
            <h2>{% trans 'Completed' %}</h2>
            <ul class="list-group">
                {% for st in completed_st %}
                <li>{{st.title}}
                    <a href="{% url 'repair_subtask' subtask_id=st.id %}" class="btn btn-link">{% trans 'Repair' %}</a>
                    <a href="{% url 'delete_subtask' subtask_id=st.id %}" class="btn btn-link">{% trans 'Delete' %}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/to_do_list/edit_tag.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}
{% block title %}
<title> Ad_como - Edit tag </title>
{% endblock%}

{% block content %}
<form method="post" class="form-group">
    {% csrf_token %}
    <label for="name">{% trans 'Name' %}</label>
    <br />
    <input class="form-control" type="text" name="name" id="name" value="{{ name }}">
    <br />
    <input class="btn btn-success" type="submit" value="submit">
</form>
{% endblock %}

templates/to_do_list/index.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}
{% block title %}
<title> Ad_como - Tasks </title>
{% endblock%}

{% block content %}
<form action="{% url 'add' %}">
    <input type="submit" class="btn btn-link" value={% trans 'Add task' %}>
</form>
{% include 'to_do_list/task_list.html' %}
{% endblock %}

templates/to_do_list/invite.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}
{% block title %}
<title> Ad_como - Invite </title>
{% endblock%}

{% block content %}
<form method="post">
    {% csrf_token %}
    <label for="iser_id">{% trans 'Username' %}</label>
    <br />
    <select class="form-control" name="user_id" id="iser_id">
        {% for user in users %}
        <option value="{{ user.id }}">{{ user }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="submit" class="btn btn-success">
</form>
{% endblock%}

templates/to_do_list/list_details.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}

{% block title %}
<title> Ad_como - Tasks </title>
{% endblock%}

{% block content %}
<h2>{{list.name}}</h2>
<div class="btn-group" role="group" aria-label="Basic example">
    {% if not list.is_private %}
    <a href="{% url 'invite' list_id=list.id %}" class="btn btn-link">{% trans 'Invite' %}</a>
    {% endif %}
    {% if superuser %}
    <a href="{% url 'edit_list' list_id=list.id  %}" class="btn btn-link">{% trans 'Edit' %}</a>
    <a href="{% url 'delete_list' list_id=list.id  %}" class="btn btn-link">{% trans 'Delete' %}</a>
    {% else %}
    <a href="{% url 'exit_list' list_id=list.id %}" class="btn btn-link">{% trans 'Exit' %}</a>
    {% endif %}
</div>
<h5>{% trans 'Users' %}:</h5>
<ul>
    {% for user in users %}
    <li>
        {{ user }}
        {% if superuser and user != request.user %}
        <form action="{% url 'kick_user' list_id=list.id  user_id=user.id %}" class="task_form">
            <input type="submit" class="btn btn-link" value={% trans 'Kick' %} />
        </form>
        {% endif %}
    </li>
    {% endfor %}
</ul>
<h5>{% trans 'Tasks' %}:</h5>
<form action="{% url 'add' %}">
    <input type="submit" class="btn btn-link" value={% trans 'Add task' %}>
</form>
{% include 'to_do_list/task_list.html' %}
{% endblock %}

templates/to_do_list/login.html
{% extends 'to_do_list/base.html' %}
{% load i18n %}
{% block title %}
<title> Ad_como - Login </title>
{% endblock%}

{% load staticfiles %}
{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
{% endblock %}

{% block content %}
    <h2 id="login_header">{% trans 'Login' %}</h2>
    <form role="form" id="login_form" class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="login" />
    </form>
    <a href="{% url 'signup' %}" class="btn btn-link">{% trans 'Sign up' %}</a>
{% endblock %}

templates/to_do_list/today.html
{% extends 'to_do_list/base.html' %}

{% block title %}
<title> Ad_como - Today </title>
{% endblock%}

{% block content %}
{% include 'to_do_list/task_list.html' %}
{% endblock %}